import Link from "next/link";
import { ChevronRight, Wand2 } from "lucide-react";
import { isTopic, topicLabel, TOPICS, type Topic } from "@gauntleet/core/topics";
import { DifficultyBadge } from "../components/DifficultyBadge";
import { GenerateForm } from "../components/GenerateForm";
import { ProblemFilters } from "../components/ProblemFilters";
import { StatusIcon } from "../components/StatusIcon";
import { listAllTopics, listProblemsWithStats, type ProblemWithStats } from "../lib/db";
import { acceptanceRate, deriveStatus, type ProblemUserStatus } from "../lib/problem-status";

export const dynamic = "force-dynamic";

type StatusFilter = "all" | ProblemUserStatus;
type DifficultyFilter = "all" | "easy" | "medium" | "hard";

interface HomeSearchParams {
  status?: string;
  difficulty?: string;
  topic?: string;
}

export default async function Home({ searchParams }: { searchParams: Promise<HomeSearchParams> }) {
  const params = await searchParams;
  const statusFilter = parseStatus(params.status);
  const difficultyFilter = parseDifficulty(params.difficulty);
  const topicFilter = parseTopic(params.topic);

  const allRows = listProblemsWithStats({
    ...(difficultyFilter !== "all" && { difficulty: difficultyFilter }),
    ...(topicFilter !== "all" && { topic: topicFilter }),
  });
  const rows = allRows.filter((p) => {
    if (statusFilter === "all") return true;
    return deriveStatus(p) === statusFilter;
  });

  const topicsInUse = listAllTopics().filter((t): t is Topic => isTopic(t));
  // Show every supported topic in the filter, ordered with in-use ones first.
  const topicSet = new Set(topicsInUse);
  const topicOptions: Topic[] = [...topicsInUse, ...TOPICS.filter((t) => !topicSet.has(t))];

  return (
    <main className="flex-1 overflow-y-auto">
      <div className="mx-auto max-w-6xl px-6 py-10">
        <section className="mb-10 max-w-2xl">
          <h1 className="text-3xl font-bold tracking-tight text-slate-900 dark:text-slate-50">
            Practice algorithmic problems generated by AI.
          </h1>
          <p className="mt-3 text-sm leading-relaxed text-slate-600 dark:text-slate-400">
            Pick a difficulty and topic. Two independent models cross-check each problem before
            it&rsquo;s shown to you, so you&rsquo;re never solving something the generator got
            wrong.
          </p>
        </section>

        <section className="mb-12">
          <SectionHeader>Generate a new problem</SectionHeader>
          <GenerateForm />
        </section>

        <section>
          <SectionHeader>
            Problems
            <span className="ml-2 rounded-full bg-slate-100 px-2 py-0.5 text-[11px] font-medium text-slate-600 dark:bg-slate-800 dark:text-slate-400">
              {rows.length}
              {rows.length !== allRows.length && ` of ${allRows.length}`}
            </span>
          </SectionHeader>

          <div className="mb-4">
            <ProblemFilters
              topics={topicOptions}
              status={statusFilter}
              difficulty={difficultyFilter}
              topic={topicFilter}
            />
          </div>

          {allRows.length === 0 ? (
            <EmptyState />
          ) : rows.length === 0 ? (
            <FilteredEmptyState />
          ) : (
            <ProblemsTable rows={rows} />
          )}
        </section>
      </div>
    </main>
  );
}

function ProblemsTable({ rows }: { rows: ProblemWithStats[] }) {
  return (
    <div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900/60">
      <table className="w-full text-sm">
        <thead className="bg-slate-50/80 text-left text-[11px] uppercase tracking-wider text-slate-500 dark:bg-slate-800/40 dark:text-slate-400">
          <tr>
            <th className="w-10 px-4 py-3 font-medium"></th>
            <th className="px-4 py-3 font-medium">Title</th>
            <th className="hidden px-4 py-3 font-medium md:table-cell">Topic</th>
            <th className="px-4 py-3 font-medium">Difficulty</th>
            <th className="hidden px-4 py-3 text-right font-medium sm:table-cell">Acceptance</th>
            <th className="w-10 px-4 py-3"></th>
          </tr>
        </thead>
        <tbody className="divide-y divide-slate-200 dark:divide-slate-800">
          {rows.map((p) => {
            const status = deriveStatus(p);
            const rate = acceptanceRate(p);
            return (
              <tr
                key={p.id}
                className="group transition-colors hover:bg-slate-50 dark:hover:bg-slate-800/30"
              >
                <td className="px-4 py-3 align-middle">
                  <StatusIcon status={status} />
                </td>
                <td className="px-4 py-3 align-middle font-medium">
                  <Link
                    href={`/p/${p.id}`}
                    className="text-slate-900 hover:underline dark:text-slate-100"
                  >
                    {p.title}
                  </Link>
                </td>
                <td className="hidden px-4 py-3 align-middle text-slate-600 md:table-cell dark:text-slate-400">
                  {topicLabel(p.topic as Topic)}
                </td>
                <td className="px-4 py-3 align-middle">
                  <DifficultyBadge difficulty={p.difficulty} />
                </td>
                <td className="hidden px-4 py-3 text-right align-middle font-mono text-xs text-slate-600 sm:table-cell dark:text-slate-400">
                  {rate === null ? (
                    <span className="text-slate-300 dark:text-slate-600">—</span>
                  ) : (
                    <span title={`${p.acceptedSubmissions} accepted of ${p.totalSubmissions}`}>
                      {rate}%
                    </span>
                  )}
                </td>
                <td className="px-4 py-3 align-middle text-right">
                  <ChevronRight className="ml-auto h-4 w-4 text-slate-300 transition-transform group-hover:translate-x-0.5 group-hover:text-slate-500 dark:text-slate-600 dark:group-hover:text-slate-300" />
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}

function SectionHeader({ children }: { children: React.ReactNode }) {
  return (
    <h2 className="mb-4 flex items-center text-sm font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400">
      {children}
    </h2>
  );
}

function EmptyState() {
  return (
    <div className="rounded-xl border border-dashed border-slate-300 bg-white px-6 py-12 text-center dark:border-slate-700 dark:bg-slate-900/40">
      <span className="mx-auto grid h-10 w-10 place-items-center rounded-full bg-slate-100 text-slate-500 dark:bg-slate-800 dark:text-slate-400">
        <Wand2 className="h-5 w-5" />
      </span>
      <p className="mt-3 text-sm font-medium text-slate-700 dark:text-slate-300">
        No validated problems yet.
      </p>
      <p className="mt-1 text-xs text-slate-500 dark:text-slate-400">
        Use the form above to generate one, or run{" "}
        <code className="rounded bg-slate-100 px-1.5 py-0.5 font-mono text-xs text-slate-700 dark:bg-slate-800 dark:text-slate-300">
          pnpm gen
        </code>{" "}
        from the CLI.
      </p>
    </div>
  );
}

function FilteredEmptyState() {
  return (
    <div className="rounded-xl border border-dashed border-slate-300 bg-white px-6 py-10 text-center dark:border-slate-700 dark:bg-slate-900/40">
      <p className="text-sm font-medium text-slate-700 dark:text-slate-300">
        No problems match these filters.
      </p>
      <p className="mt-1 text-xs text-slate-500 dark:text-slate-400">
        Adjust the chips above or generate a new problem.
      </p>
    </div>
  );
}

function parseStatus(raw: string | undefined): StatusFilter {
  if (raw === "solved" || raw === "attempted" || raw === "unsolved") return raw;
  return "all";
}

function parseDifficulty(raw: string | undefined): DifficultyFilter {
  if (raw === "easy" || raw === "medium" || raw === "hard") return raw;
  return "all";
}

function parseTopic(raw: string | undefined): string {
  if (typeof raw === "string" && raw.length > 0 && isTopic(raw)) return raw;
  return "all";
}
