export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-8">
      <h1 className="text-4xl font-bold tracking-tight">Gauntleet</h1>
      <p className="mt-4 max-w-md text-center text-gray-600 dark:text-gray-400">
        Practice algorithmic problems generated by AI. Scaffold in place — features coming soon.
      </p>
    </main>
  );
}
