import Link from "next/link";
import { notFound } from "next/navigation";
import { DifficultyBadge } from "../../../components/DifficultyBadge";
import { ProblemEditor } from "../../../components/ProblemEditor";
import { ProblemMarkdown } from "../../../components/ProblemMarkdown";
import { SampleTests } from "../../../components/SampleTests";
import { getProblem } from "../../../lib/db";
import { formatStarterCode } from "../../../lib/problem-format";

export const dynamic = "force-dynamic";

export default async function ProblemPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const problem = getProblem(id);
  if (!problem) notFound();

  const starterCode = formatStarterCode({
    functionName: problem.functionName,
    parameters: problem.parameters,
    returnType: problem.returnType,
  });

  return (
    <div className="flex h-screen flex-col">
      <header className="flex flex-shrink-0 items-center justify-between border-b border-slate-200 bg-white px-4 py-3 dark:border-slate-800 dark:bg-slate-950">
        <div className="flex items-center gap-3">
          <Link
            href="/"
            className="text-sm text-slate-500 hover:text-slate-900 dark:text-slate-400 dark:hover:text-slate-100"
          >
            ← Problems
          </Link>
          <span className="text-slate-300 dark:text-slate-700">|</span>
          <h1 className="text-base font-semibold">{problem.title}</h1>
          <DifficultyBadge difficulty={problem.difficulty} />
          <span className="text-xs text-slate-500 dark:text-slate-400">{problem.topic}</span>
        </div>
        <span className="text-xs text-slate-400 dark:text-slate-500">
          generated by {problem.generatorModel}
        </span>
      </header>

      <main className="grid min-h-0 flex-1 grid-cols-1 md:grid-cols-2">
        <section className="overflow-y-auto border-slate-200 px-6 py-5 md:border-r dark:border-slate-800">
          <ProblemMarkdown>{problem.statement}</ProblemMarkdown>
          <h3 className="mt-6 mb-2 text-sm font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400">
            Sample tests
          </h3>
          <SampleTests tests={problem.sampleTests} />
          <h3 className="mt-6 mb-2 text-sm font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400">
            Submissions
          </h3>
          <p className="text-xs text-slate-500 dark:text-slate-400">
            Submission history will appear here once judging is wired up (PR #7).
          </p>
        </section>
        <section className="min-h-0">
          <ProblemEditor problemId={problem.id} starterCode={starterCode} />
        </section>
      </main>
    </div>
  );
}
